name: Bug Report
description: Report an issue to help us improve
title: "Provide a brief, clear description of the bug"
labels: ["bug"]

body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Brief description of the issue.

  - type: dropdown
    id: environment
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Other

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Step one
        2. Step two

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      placeholder: Paste any relevant logs or screenshots.

  - type: textarea
    id: config
    attributes:
      label: Configuration Files
      description: VS Code settings.json / other configs if applicable.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      placeholder: Any other info?
