package com.thealgorithms.hashes;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;

/**
 * The SHA1 class provides a method to generate the SHA-1 hash for a given string.
 * SHA-1 (Secure Hash Algorithm 1) is a cryptographic hash function that produces
 * a 160-bit (20-byte) hash value. It is commonly used for data integrity verification,
 * although it is no longer considered secure for cryptographic purposes.
 * 
 * @see <a href="https://en.wikipedia.org/wiki/SHA-1">SHA-1 on Wikipedia</a>
 */
public class SHA1 {

    /**
     * Generates the SHA-1 hash of the input string.
     *
     * @param input the string to be hashed
     * @return the SHA-1 hash as a hexadecimal string
     */
    public static String getSha1(String input) {
        try {
            // Create a MessageDigest instance for SHA-1
            MessageDigest md = MessageDigest.getInstance("SHA-1");
            
            // Compute the SHA-1 digest of the input string
            byte[] messageDigest = md.digest(input.getBytes());
            
            // Convert the byte array into a BigInteger to get the hash in hexadecimal format
            BigInteger no = new BigInteger(1, messageDigest);
            
            // Convert the BigInteger to a hexadecimal string
            String hashtext = no.toString(16);

            // Pad with leading zeros to ensure the hash is 32 characters long
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            
            // Return the generated SHA-1 hash
            return hashtext;
        } catch (NoSuchAlgorithmException e) {
            // Handle the case where SHA-1 algorithm is not available
            throw new RuntimeException(e);
        }
    }

    /**
     * The main method that takes user input, computes its SHA-1 hash, and prints the result.
     *
     * @param args command-line arguments
     * @throws NoSuchAlgorithmException if the SHA-1 algorithm is not available
     */
    public static void main(String args[]) throws NoSuchAlgorithmException {
        // Create a Scanner object to read input from the user
        Scanner scanner = new Scanner(System.in);
        
        // Prompt the user to enter a string to hash
        System.out.print("Enter the string to hash: ");
        
        // Read the input string from the user
        String s = scanner.nextLine();
        
        // Compute the SHA-1 hash of the input string and print it
        System.out.println("Your HashCode Generated by SHA-1 is: " + getSha1(s));
        
        // Close the Scanner object
        scanner.close();
    }
}