package ProjectEuler;

/**
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 * The first ten terms would be:
 * <p>
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * <p>
 * Let us list the factors of the first seven triangle numbers:
 * <p>
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * <p>
 * What is the value of the first triangle number to have over five hundred divisors?
 * <p>
 * link: https://projecteuler.net/problem=12
 */
public class Problem12 {

    public static void main(String[] args) {
        System.out.println(new Problem12().run());
    }


    /*
     * Computers are fast, so we can implement this solution directly without any clever math.
     */
    public String run() {
        int triangle = 0;
        for (int i = 1; ; i++) {
            if (Integer.MAX_VALUE - triangle < i)
                throw new ArithmeticException("Overflow");
            triangle += i;  // This is the ith triangle number, i.e. num = 1 + 2 + ... + i = i * (i + 1) / 2
            if (countDivisors(triangle) > 500)
                return Integer.toString(triangle);
        }
    }


    // Returns the number of integers in the range [1, n] that divide n.
    private static int countDivisors(int n) {
        int count = 0;
        int end = Library.sqrt(n);
        for (int i = 1; i < end; i++) {
            if (n % i == 0)
                count += 2;
        }
        if (end * end == n)  // Perfect square
            count++;
        return count;
    }

}